### ISSUE TITLE
Failed to get installments. Use cardForm callbacks to intercept the error  TypeError: Cannot read property 'payer_costs' of undefined

### ISSUE THREAD

**Issue by MateoArgalle** [mercadopago/sdk-js#14]
Hello, I am using the SDK that it offers but when I want to obtain the installments I get the following error

![image](https://user-images.githubusercontent.com/58223373/115931553-edddb100-a450-11eb-85da-5793bc427c61.png)
 
 This is my code
![code](https://user-images.githubusercontent.com/58223373/115932135-f2ef3000-a451-11eb-8a70-355cbfb8cc99.png)

**Comment by NicholasPedroso** [comment]
Hello @MateoArgalle 

Could you share the complete code on how you are doing this integration? And please send it as text, not as an image,

Thanks

**Comment by MateoArgalle** [comment]
I have the following error initializing the mercadopago package.

The following I do it from the front with vuejs to be able to initialize the form.

import { MercadoPago } from 'mercadopago'
let publickey =  MercadoPago.setPublishableKey("TEST-94f7a96e-cbd4-44e5-a676-6b0ca0952628");

and I have the following error

![image](https://user-images.githubusercontent.com/58223373/116427058-4cb47900-a809-11eb-8af0-f823b512bf3d.png)

**Comment by NicholasPedroso** [comment]
Hi,

There is no method `setPublishableKey` in MercadoPago.js V2. And the way you are importing: `import { MercadoPago } from 'mercadopago'` its unsual, when you import `mercadopago` package from npm, you are using the backend SDK for nodeJS.

To be able to help you with more questions on this subject, please contact us from our support channel so that we can respond as soon as possible.
