### ISSUE TITLE
Execution function after modal closing

### ISSUE THREAD

**Issue by pauloalmeidasilva** [mercadopago/sdk-js#18]
It will be interesting to create a function in case of a successful or failed payment.

For example, if the payment is completed successfully, run that function from the script.

**Comment by NicholasPedroso** [comment]
Hi @pauloalmeidasilva,

please, could you add that idea within [Discussions -> Ideas](https://github.com/mercadopago/sdk-js/discussions/categories/ideas)? And also with a little more details explaining the need; implementation ideas (examples), and expected result.

We will be analyzing each suggestion carefully.

Since this is not an issue, I’m closing,

Thanks

we appreciate your
