### ISSUE TITLE
onIssuersReceived callback is not call 

### ISSUE THREAD

**Issue by guidopontet** [mercadopago/sdk-js#50]
**Describe the bug**
`onIssuersReceived` is not fired with some `cardNumber`

**To Reproduce**
For example, when i use Mastercard cardNumber (5031 7557 3453 0604 ~ [from Testing](https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-api/v1/testing) ~) everything works fine, `onIssuersReceived` callback is call. But when i use a real cardNumber or even Visa (4509 9535 6623 3704) or American Express (3711 803032 57522) from Testing, onIssuersReceived is not call.

**Expected behavior**
`onIssuersReceived` is call for every cardNumber

**Browser**: 
Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by lucmantovani** [comment]
Hello @guidopontet!

It is not always that the `onIssuersReceived` callback will be called.
It will be triggered when there was a call to `getIssuers`, which happens when the field `additional_info_needed` from the `paymentMethods` has the entry `issuer_id`.

A callback that is always triggered when the BIN is inserted is `onPaymentMethodsReceived`.
